### ISSUE TITLE
개발하고자 하는 사이트의 구체적인 방향 제시

### ISSUE THREAD

**Issue by Naesung** [Teaddy-Studio/WebSite#1]
개발하고자 하는 사이트의 구체적인 방향을 제시해주시면 좋을 것 같네요. 저도 참가합니다.

**Comment by comjun04** [comment]
@seomingyu11 @Naesung 어떤 사이트를 개발하는지 알려주실 수 있나요?

**Comment by seomingyu11** [comment]
@Naesung 
> 개발하고자 하는 사이트의 구체적인 방향을 제시해주시면 좋을 것 같네요. 저도 참가합니다.

1. "개발하고자 하는 사이트의 구체적인 방향을 제시"
일단 Teaddy Brand(태디TV, 태디트위치, Teaddy Stduio(Discord), Teaddy Stduio(Github) 등등) 을 소개하는 페이지로 방향을 잡았긴 합니다만, 상황에 따라 제가 속한 크루에 관한 소개 페이지도 추가 될 수 있음을 알려드립니다.

2. "저도 참가합니다"
일단 참가한다고 메세지 남겨준 것에 대해 감사합니다.
아마도 참가하기 위해서 Developr 신청해야 될 것 같은데..
일단 개발팀장님께 물어보도록 하겠습니다.

**Comment by seomingyu11** [comment]
> @seomingyu11 @Naesung 어떤 사이트를 개발하는지 알려주실 수 있나요?

1. "어떤 사이트를 개발하는지"
Teaddy Brand 공식 페이지를 만들 예정입니다.
그 공식 페이지 안의 내용에는 Teaddy Brand(태디TV, 태디트위치, Teaddy Studio(Discord), Teaddy Studio(Github) 등등)을 소개하는 페이지와 상황에 따라 제가 소속되어 있는 크루에 관한 페이지도 추가 될 수 있음을 알려드립니다.

**Comment by seomingyu11** [comment]
@Naesung 
> 개발하고자 하는 사이트의 구체적인 방향을 제시해주시면 좋을 것 같네요. 저도 참가합니다.

2. "저도 참가합니다"
개발팀장님께 물어본 결과, 함께 참여하실 수 있게 되었습니다!
답변일 작성 기준, Discord 닉네임 및 Tag가 "192.03#0001"이 맞는지 확인해 주시기 바라며, 맞다고 확인 후, 바로 역할 넣어드리도록 하겠습니다.
혹시라도, Discord 닉네임 및 Tag가 다를 경우 알려주세요!
